### ISSUE TITLE
Sandia D on OF10

### ISSUE THREAD

**Issue by manaman8** [Aalto-CFD/DLBFoam-Advanced-Tutorials#6]
Hi, I am trying to run the example case Sandia Flame D on OFv10 and keep running into the below error while running decomposePar:

`/DLBFoam-Advanced-Tutorials/Sandia_D/0/U/boundaryField/inletJet: In member function ‘virtual void Foam::inletJetFixedValueUFixedValueFvPatchVectorField::updateCoeffs()’:
/DLBFoam-Advanced-Tutorials/Sandia_D/0/U/boundaryField/inletJet:57:55: error: use of deleted function ‘Foam::fixedValueFvPatchField<Type>::fixedValueFvPatchField(const Foam::fixedValueFvPatchField<Type>&) [with Type = Foam::Vector<double>]’
In file included from /OpenFOAM-10/src/finiteVolume/lnInclude/fixedValueFvPatchFields.H:29,
                 from codedFixedValueFvPatchFieldTemplate.H:38,
                 from codedFixedValueFvPatchFieldTemplate.C:26:
/OpenFOAM-10/src/finiteVolume/lnInclude/fixedValueFvPatchField.H:107:9: note: declared here
  107 |         fixedValueFvPatchField(const fixedValueFvPatchField<Type>&) = delete;`

This refers to the inlet turbulence generator code. I am not sure if this is a version issue, nor do I know enough to debug. 

I am running the example case as is (without any modification). 

Appreciate if you can shed any light regarding this. 

Mana

**Comment by moreff** [comment]
Hi, 

The cases in this repository were made for OpenFOAM 8, so some things might need to be changed in order to make them work in other versions.

In order to make it work with OpenFOAM 10, you can replace these 2 lines:
https://github.com/Aalto-CFD/DLBFoam-Advanced-Tutorials/blob/e190204ea249d2001cd476d6b3ed8f7d9b7a2108/Sandia_D/0.orig/U#L57
https://github.com/Aalto-CFD/DLBFoam-Advanced-Tutorials/blob/e190204ea249d2001cd476d6b3ed8f7d9b7a2108/Sandia_D/0.orig/U#L104

with 
```fixedValueFvPatchVectorField myPatch(*this, this->db().lookupObjectRef<volVectorField>("U"));```

**Comment by manaman8** [comment]
Thanks moreff! Worked perfectly
